version: '3'
services:
   nginx:
     build: ./images/nginx/
     ports:
      - "80:80"
      - "443:443"
     volumes:
      - ./site/html:/var/www/html
      - ./images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./ssl.conf:/etc/nginx/ssl.conf
   apache2:
     build: ./images/apache2/
     volumes:
      - ./site/html:/var/www/html

   mysql:
     build: ./images/mysql/
     volumes:
      - ./site/db:/docker-entrypoint-initdb.d
