version: '3'
services:
   nginx:
     build: ./images/nginx/
     ports:
      - "80:80"
     volumes:
      - ./site/html:/var/www/html
      - ./images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

   apache2:
     build: ./images/apache2/
     ports: 
      - "8080:80"
     volumes:
      - ./site/html:/var/www/html

   mysql:
     build: ./images/mysql/
     ports: 
      - "3306:3306"
     volumes:
      - ./site/db:/docker-entrypoint-initdb.d
